### Load  Basic Libraries

In [1]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=sns.load_dataset("iris")

In [4]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
data["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
data1=data[data["species"]!="setosa"]

In [10]:
data1.head(2)

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor

In [12]:
data1["species"].unique()

array(['versicolor', 'virginica'], dtype=object)

In [13]:
data1["species"]=data1["species"].map({"versicolor":0,"virginica":1})

C:\Users\shikha choudhary\AppData\Local\Temp\ipykernel_15992\3394530424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["species"]=data1["species"].map({"versicolor":0,"virginica":1})

In [15]:
data1["species"].unique()

array([0, 1], dtype=int64)

In [16]:
data1.head(2)

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0

### Data division part

In [17]:
x=data1.iloc[:,:-1]      # -1-1=-2
y=data1.iloc[:,-1]

In [19]:
x.head(2)

    sepal_length  sepal_width  petal_length  petal_width
50           7.0          3.2           4.7          1.4
51           6.4          3.2           4.5          1.5

In [20]:
y.head()

50    0
51    0
52    0
53    0
54    0
Name: species, dtype: int64

### Data Splition in Train and Test

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=42)

In [23]:
x_train.head()

     sepal_length  sepal_width  petal_length  petal_width
65            6.7          3.1           4.4          1.4
90            5.5          2.6           4.4          1.2
146           6.3          2.5           5.0          1.9
59            5.2          2.7           3.9          1.4
122           7.7          2.8           6.7          2.0

In [24]:
y_train.head()

65     0
90     0
146    1
59     0
122    1
Name: species, dtype: int64

### Model Building part

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
logistic_model=LogisticRegression()

In [27]:
logistic_model.fit(x_train,y_train)    ## 1/1+e^-z  , z=[m1x1+m2x2+m3x3+m4x4]+C    , z=x1+2x2+2.5x3+3x4+10

LogisticRegression()