### Load Basic Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=sns.load_dataset("iris")

In [4]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
data1=data[data["species"]!="setosa"]

In [7]:
data1["species"].unique()

array(['versicolor', 'virginica'], dtype=object)

In [8]:
data1["species"]=data1["species"].map({"versicolor":0,"virginica":1})

C:\Users\shikha choudhary\AppData\Local\Temp\ipykernel_824\3394530424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["species"]=data1["species"].map({"versicolor":0,"virginica":1})

In [19]:
data1

     sepal_length  sepal_width  petal_length  petal_width  species
50            7.0          3.2           4.7          1.4        0
51            6.4          3.2           4.5          1.5        0
52            6.9          3.1           4.9          1.5        0
53            5.5          2.3           4.0          1.3        0
54            6.5          2.8           4.6          1.5        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

[100 rows x 5 columns]

In [11]:
data1["species"].unique()

array([0, 1], dtype=int64)

### Divide in input and output

In [12]:
x=data1.iloc[:,:-1]
y=data1.iloc[:,-1]

In [14]:
x.head(2)

    sepal_length  sepal_width  petal_length  petal_width
50           7.0          3.2           4.7          1.4
51           6.4          3.2           4.5          1.5

In [17]:
y.head()

50    0
51    0
52    0
53    0
54    0
Name: species, dtype: int64

### Data Splition

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [23]:
x_train.head()

     sepal_length  sepal_width  petal_length  petal_width
65            6.7          3.1           4.4          1.4
90            5.5          2.6           4.4          1.2
146           6.3          2.5           5.0          1.9
59            5.2          2.7           3.9          1.4
122           7.7          2.8           6.7          2.0

In [25]:
y_train.head()

65     0
90     0
146    1
59     0
122    1
Name: species, dtype: int64

### Model  Building Part

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logistic_model=LogisticRegression()
logistic_model.fit(x_train,y_train)      # 1/1+e^-z==> z=m1x1+m2x2+m3x3+m4x4+C

LogisticRegression()

In [28]:
y_pred=logistic_model.predict(x_test)

In [29]:
y_test,y_pred

(133    1
 103    1
 120    1
 95     0
 94     0
 89     0
 72     0
 130    1
 60     0
 50     0
 68     0
 80     0
 123    1
 83     0
 140    1
 54     0
 126    1
 127    1
 62     0
 81     0
 105    1
 138    1
 76     0
 92     0
 119    1
 Name: species, dtype: int64,
 array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 0, 1], dtype=int64))

In [31]:
x_pred=logistic_model.predict(x_train)

### Model Evaluation

In [33]:
from sklearn.metrics import accuracy_score,classification_report

In [34]:
print("Training Accuracy: ",accuracy_score(y_train,x_pred))
print("Testing Accuracy: ",accuracy_score(y_test,y_pred))

Training Accuracy:  0.9733333333333334
Testing Accuracy:  0.92

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.91      0.91      0.91        11

    accuracy                           0.92        25
   macro avg       0.92      0.92      0.92        25
weighted avg       0.92      0.92      0.92        25